name: Socgent
version:
  majorVersion: 1 # raise this number for major revamp/refactoring
  minorVersion: 0 # raise this number for feature release or regular release, max 99
  patchVersion: 0 # raise this number for hotfix release, max 99
  bumpVersion: 0 # raise this number for daily / dog-food build, max 99
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    version: 1.23.1
  Moya:
    url: https://github.com/Moya/Moya
    version: 15.0.3  
settings:
  base:
    SWIFT_VERSION: 6.2
configFiles:
  Debug: Configs/Release.xcconfig
  Release: Configs/Release.xcconfig
targets:
  Socgent:
    type: application
    platform: iOS
    configFiles:
      Debug: Configs/Release.xcconfig
      Release: Configs/Release.xcconfig
    deploymentTarget: "17.0"
    sources:
      - path: Socgent        
    info:
      path: Socgent/Resources/Plist/Info.plist
      properties:
        CFBundleDisplayName: Socgent
        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: com.abdhilabs.socgent
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        ITSAppUsesNonExemptEncryption: false
        UILaunchScreen:
          UILaunchScreen: {}
        ConfigVariables:
          X_BEARER_TOKEN: "$(X_BEARER_TOKEN)"
    dependencies:
      - package: ComposableArchitecture
      - package: Moya 
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.abdhilabs.socgent
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1000000
        INFOPLIST_KEY_CFBundleDisplayName: "Socgent"
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: com.abdhilabs.socgent
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: true
    postBuildScripts:
      # - name: Firebase Crashlytics
      #   script: |
      #     "${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
      #   inputFiles:
      #     - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
      #     - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
      - name: Linter
        script: |
          if [[ "$(uname -m)" == arm64 ]]; then
            export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftlint > /dev/null; then
            swiftlint --config "${SRCROOT}/.swiftlint.yml"
          fi
        basedOnDependencyAnalysis: false
        showEnvVars: false
  SocgentTests:
    type: bundle.unit-test
    platform: iOS
    configFiles:
      Debug: Configs/Release.xcconfig
      Release: Configs/Release.xcconfig
    deploymentTarget: "16.0"
    sources:
      - path: SocgentTests
    dependencies:
      - target: Socgent
      - package: ComposableArchitecture
